twist_mux:
  ros__parameters:
    topics:
      navigation:
        topic   : nav_vel
        timeout : 0.5
        priority: 10
        stamped : true

      joystick:
        topic   : joy_vel
        timeout : 0.5
        priority: 100
        stamped : true